name: Tourism Project Pipeline

on:
  push:
    branches:
      - main  # Automatically triggers on push to the main branch

jobs:

  data-preparation-and-registration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install Dependencies
        run: pip install -r .github/workflows/scripts/workflow_requirements.txt
      - name: Register and Split Data
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: python .github/workflows/scripts/register_and_split_data.py

  model-training-and-registration:
    needs: data-preparation-and-registration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install Dependencies
        run: pip install -r .github/workflows/scripts/workflow_requirements.txt
      - name: Create MLflow Tracking Directory
        run: mkdir -p mlruns
      - name: Model Training and Registration
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: python tourism_project/.github/workflows/scripts/train_and_deploy_model.py

  deploy-streamlit-space:
    needs: model-training-and-registration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install Dependencies
        run: pip install -r .github/workflows/scripts/workflow_requirements.txt
      - name: Push files to Frontend Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: python .github/workflows/scripts/deploy_streamlit_app.py
